FROM nginx
MAINTAINER Florent APPOINTAIRE <florent.appointaire@gmail.com>
COPY index.html /usr/share/nginx/html/
COPY fondecran.html /usr/share/nginx/html/
COPY planning.html /usr/share/nginx/html/
COPY Sources/ /usr/share/nginx/html/Sources/